// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKXxhnv_gGvpLZ1-GQ0WJdNc-JjgmTJw',
    appId: '1:770111659996:web:5a55c171bc87b6517ef919',
    messagingSenderId: '770111659996',
    projectId: 'instartk',
    authDomain: 'instartk.firebaseapp.com',
    storageBucket: 'instartk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDpEEQ84cm3Bg4Nh8LB4gOn3mA7I3QKKc',
    appId: '1:770111659996:android:d477daadba79d6407ef919',
    messagingSenderId: '770111659996',
    projectId: 'instartk',
    storageBucket: 'instartk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClwye756o04eavLUhyyBlJ_gCpNsCKRfk',
    appId: '1:770111659996:ios:fec9f25e07fd16e47ef919',
    messagingSenderId: '770111659996',
    projectId: 'instartk',
    storageBucket: 'instartk.appspot.com',
    iosClientId: '770111659996-vkg3k6g8m6ismm76ihk17ni97lhvtmq0.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.instagramCloneCourseRtk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClwye756o04eavLUhyyBlJ_gCpNsCKRfk',
    appId: '1:770111659996:ios:88eebd33f66b33f57ef919',
    messagingSenderId: '770111659996',
    projectId: 'instartk',
    storageBucket: 'instartk.appspot.com',
    iosClientId: '770111659996-q27nvpgdd5cird56a7fi0u60f3qo6p3a.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.instagramCloneCourseRtk.RunnerTests',
  );
}
